#document settings
title: API Release Kit
description: Suggested elements for API production.  
url: http://gbinal.github.com/jekyll-template
repo_url: http://github.com/gbinal/jekyll-template

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true