#document settings
title: API Release Kit
description: Suggested elements for API production.  
url: http://gbinal.github.com/api-release-kit-2
repo_url: http://github.com/gbinal/api-release-kit-2

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true