#document settings
title: API Release Kit
description: The elements that make up a well-rounded API release.  
url: http://gbinal.github.com/api-release-kit
repo_url: http://github.com/gbinal/api-release-kit

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true